use crate::core::{event, security};
use crate::db::Db;
use anyhow::{anyhow, Result};
use tracing::{error, info};
use uuid::Uuid;

pub async fn run(db: &Db, app: &tauri::AppHandle, issue_id: &str) -> Result<()> {
    // Load issue
    let issue = sqlx::query_as::<_, crate::models::issue::Issue>("SELECT * FROM issues WHERE id=?")
        .bind(issue_id)
        .fetch_optional(db)
        .await?
        .ok_or_else(|| anyhow!("issue {} not found", issue_id))?;

    // Security check
    if security::has_obvious_injection(&issue.title)
        || security::has_obvious_injection(&issue.description)
    {
        error!(
            "issue {} failed security check — possible injection",
            issue_id
        );
        sqlx::query("UPDATE issues SET status='rejected', updated_at=datetime('now') WHERE id=?")
            .bind(issue_id)
            .execute(db)
            .await?;
        return Err(anyhow!("security check failed for issue {}", issue_id));
    }

    // Layer 1 (design §4.3): deeper LLM sanitization beyond the regex fast-reject.
    // Trusted internal sources skip the LLM check; external sources always run it.
    // Gracefully degrades to "allow" when the claude CLI is unavailable.
    // "github" is intentionally NOT trusted: GitHub issue text is externally
    // authored (anyone can open an issue) and must run the LLM sanitizer.
    // "proposer" IS trusted: these issues are generated by AutoForge's own
    // auto-supply proposer (intake/proposer.rs) and already pass proposer
    // self-verification — they are internal machine output, not external user
    // input. Running them through the injection sanitizer false-positives on
    // legitimate self-referential feature requests (e.g. "新增 AI 角色/绑定模型")
    // that the prompt mistakes for attempts to override AI system constraints.
    const TRUSTED_SOURCES: &[&str] = &[
        "scan", "monitor", "todo_scan", "security_audit", "ci_monitor", "proposer",
    ];
    if !TRUSTED_SOURCES.contains(&issue.source_type.as_str()) {
        let combined = format!("{}\n{}", issue.title, issue.description);
        if !crate::agents::local_claude::safety_check(db, &combined).await {
            error!("issue {} rejected by Layer 1 LLM sanitizer", issue_id);
            sqlx::query(
                "UPDATE issues SET status='rejected', updated_at=datetime('now') WHERE id=?",
            )
            .bind(issue_id)
            .execute(db)
            .await?;
            return Err(anyhow!("layer 1 sanitizer rejected issue {}", issue_id));
        }
    }

    info!("analyzing issue: {} — {}", issue_id, issue.title);

    // Load project context from local repo path
    let repo_path: Option<String> = sqlx::query_as::<_, crate::models::project::Project>(
        "SELECT * FROM projects WHERE id=?",
    )
    .bind(&issue.project_id)
    .fetch_optional(db)
    .await
    .ok()
    .flatten()
    .filter(|p| !p.repo_path.is_empty())
    .map(|p| p.repo_path);

    let project_context: Option<String> = if let Some(path) = repo_path {
        let ctx = crate::agents::analysis::build_project_context(&path).await;
        if ctx.trim().is_empty() { None } else { Some(ctx) }
    } else {
        None
    };

    // Run analysis (uses the analysis Agent's bound custom LLM; CLI only as fallback).
    // Distinguish a *genuine failure* (LLM transport error or an empty response)
    // from a real low-score result. A failure used to be silently swallowed by
    // `unwrap_or_default()`, parking the issue at pending_issue_review with a blank,
    // misleading 0.5/0.5 analysis. Instead we now surface it: park the issue at
    // `analysis_failed` so 需求审核 shows the raw error + a "重新分析" entry point.
    let trace_tags = crate::core::trace::TraceTags {
        issue_id: Some(issue_id.to_string()),
        project_id: Some(issue.project_id.clone()),
        ..Default::default()
    };
    // D1：Bug 载体增强——把复现/环境/期望/实际作为高质量输入并入描述，喂自主分析与修复。
    let enriched_desc = {
        let mut d = issue.description.clone();
        let mut push = |label: &str, val: &Option<String>| {
            if let Some(s) = val.as_deref().map(str::trim).filter(|s| !s.is_empty()) {
                d.push_str(&format!("\n\n## {}\n{}", label, s));
            }
        };
        push("复现步骤", &issue.repro_steps);
        push("环境", &issue.environment);
        push("期望结果", &issue.expected);
        push("实际结果", &issue.actual);
        // 需求审核 管理员补充意见：上一轮分析后人工提出，需据此重新评估该需求。
        // 作为高优先输入并入描述，引导本轮分析。消费后下方清空，保证一次性。
        push("管理员补充意见（请据此重新评估本需求）", &issue.review_feedback);
        d
    };
    // 一次性消费补充意见：本轮已并入分析输入，立即清空，避免后续重试重复注入。
    if issue.review_feedback.as_deref().map(str::trim).is_some_and(|s| !s.is_empty()) {
        let _ = sqlx::query("UPDATE issues SET review_feedback=NULL WHERE id=?")
            .bind(issue_id)
            .execute(db)
            .await;
    }
    // Innate: traced recall of past analysis experience (project ⊕ shared). Keyed
    // by issue → its outcome is written back at review_1 (approve = up / reject =
    // down), closing the analysis calibration loop. Injected into the analysis
    // prompt below; the trace is stashed only when analysis actually reaches
    // review_1 (success path), so a failed analysis doesn't leave a dangling row.
    let recall = crate::knowledge::kb_recall_traced(
        &issue.project_id,
        &format!("{} {}", issue.title, enriched_desc),
    )
    .await;
    let recalled = Some(recall.text.as_str()).filter(|s| !s.trim().is_empty());
    // 需求图片附件：把 kind='image' 的附件解析为磁盘绝对路径，喂给分析 Agent。
    // 仅当分析 Agent 绑定的 LLM supports_vision=1 时图片才真正内联（analyze 内部判定），
    // 否则静默忽略，纯文本分析（零回归）。
    let image_paths: Vec<std::path::PathBuf> = sqlx::query_as::<_, (String,)>(
        "SELECT rel_path FROM issue_attachments WHERE issue_id=? AND kind='image' ORDER BY created_at ASC",
    )
    .bind(issue_id)
    .fetch_all(db)
    .await
    .unwrap_or_default()
    .into_iter()
    .filter_map(|(rel,)| {
        crate::commands::attachments_common::attachment_path_from_rel(&rel).ok()
    })
    .filter(|p| p.exists())
    .collect();
    let result = match crate::core::trace::with_tags(
        trace_tags,
        crate::agents::analysis::analyze(
            db,
            &issue.title,
            &enriched_desc,
            project_context.as_deref(),
            Some(issue.project_id.as_str()),
            recalled,
            &image_paths,
        ),
    )
    .await
    {
        Ok(r) if !r.raw_output.trim().is_empty() => r,
        outcome => {
            let err = match outcome {
                Err(e) => e.to_string(),
                _ => "分析模型返回为空（可能是超时、限流或未配置可用的 LLM）".to_string(),
            };
            error!("analysis failed for issue {}: {}", issue_id, err);
            // Persist the failure so the audit page can show the raw error and
            // offer a retry, rather than a fabricated default analysis.
            let analysis_id = Uuid::new_v4().to_string();
            let _ = sqlx::query(
                "INSERT OR REPLACE INTO issue_analyses
                 (id, issue_id, authenticity_score, feasibility_score, priority_suggestion,
                  category_suggestion, severity_suggestion, affected_modules, analysis_summary,
                  raw_llm_output, analysis_json)
                 VALUES (?, ?, 0, 0, 5, '', 'medium', '[]', ?, ?, '{}')",
            )
            .bind(&analysis_id)
            .bind(&issue.id)
            .bind(format!("自动分析失败：{}", err))
            .bind(&err)
            .execute(db)
            .await;
            sqlx::query(
                "UPDATE issues SET status='analysis_failed', updated_at=datetime('now') WHERE id=?",
            )
            .bind(&issue.id)
            .execute(db)
            .await?;
            crate::core::notify::dispatch(db, "analysis_failed", "需求分析失败", &issue.title).await;
            // Reuse AnalysisCompleted so the frontend reloads the issue list and
            // shows the analysis_failed status (no need for a new event variant).
            event::emit(
                app,
                event::AppEvent::AnalysisCompleted {
                    issue_id: issue.id.clone(),
                },
            );
            return Err(anyhow!("analysis failed for issue {}: {}", issue_id, err));
        }
    };

    // Analysis succeeded and will land at review_1 — stash the recall trace so its
    // human verdict (approve/reject) calibrates the recalled analysis chunks.
    crate::knowledge::store_recall_trace(db, "issue", issue_id, &issue.project_id, &recall).await;

    // Persist analysis
    let analysis_id = Uuid::new_v4().to_string();
    let affected_modules_json = serde_json::to_string(&result.affected_modules)?;
    sqlx::query(
        "INSERT OR REPLACE INTO issue_analyses
         (id, issue_id, authenticity_score, feasibility_score, priority_suggestion,
          category_suggestion, severity_suggestion, affected_modules, analysis_summary,
          raw_llm_output, analysis_json)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
    )
    .bind(&analysis_id)
    .bind(&issue.id)
    .bind(result.authenticity_score)
    .bind(result.feasibility_score)
    .bind(result.priority_suggestion)
    .bind(&result.category_suggestion)
    .bind(&result.severity_suggestion)
    .bind(&affected_modules_json)
    .bind(&result.analysis_summary)
    .bind(&result.raw_output)
    .bind(&result.analysis_json)
    .execute(db)
    .await?;

    // Dual-write 到统一产出表 agent_outputs（schema 驱动 agent 的统一落点）：保留 issue_analyses
    // 向后兼容的同时，让需求分析与测试等环节产出在同一存储里按 issue 串成流水线、按 trace_id 下钻。
    crate::agents::schema::record(
        db,
        "analysis",
        &result.spec.schema_version,
        "issue",
        &issue.id,
        Some(&issue.project_id),
        result.trace_id.as_deref(),
        "ok",
        &result.analysis_json,
        &result.raw_output,
    )
    .await;

    // Update issue status and promote analysis suggestions into queue fields.
    sqlx::query(
        "UPDATE issues
         SET status='pending_issue_review',
             priority=?,
             category=?,
             severity=?,
             updated_at=datetime('now')
         WHERE id=?",
    )
    .bind(result.priority_suggestion)
    .bind(&result.category_suggestion)
    .bind(&result.severity_suggestion)
    .bind(&issue.id)
    .execute(db)
    .await?;

    // D2：把 AI 生成的验收标准固化到 issues.acceptance_json（供人审改 + code agent DoD + review_2 核对）。
    if let Ok(v) = serde_json::from_str::<serde_json::Value>(&result.analysis_json) {
        if let Some(ac) = v.get("acceptance_criteria").filter(|a| !a.is_null()) {
            if let Ok(ac_str) = serde_json::to_string(ac) {
                let _ = sqlx::query("UPDATE issues SET acceptance_json=? WHERE id=?")
                    .bind(&ac_str)
                    .bind(&issue.id)
                    .execute(db)
                    .await;
            }
        }
    }

    // Emit events
    event::emit(
        app,
        event::AppEvent::AnalysisCompleted {
            issue_id: issue.id.clone(),
        },
    );

    event::emit(
        app,
        event::AppEvent::ReviewNeeded {
            cr_id: String::new(),
            issue_title: issue.title.clone(),
            stage: 1,
        },
    );

    info!("analysis completed for issue {}", issue_id);
    Ok(())
}
